# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Config
    modelClass: \Ebussola\Statefull\Models\UrlDynamicImporter
    list: $/ebussola/statefull/models/urldynamic/full_columns.yaml

export:
    title: Export Config
    modelClass: \Ebussola\Statefull\Models\UrlDynamicExporter
    list: $/ebussola/statefull/models/urldynamic/full_columns.yaml